DB_VISUAL_INSPECTION = "visualInspection"

COLLECTION_MODEL_LIST = 'modelList'
COLLECTION_FILE_UPLOAD_COUNTER = 'fileUploadCounter'

COLLECTION_FILE_UPLOAD_REQUEST_DETAILS = 'fileUploadRequest'

COLLECTION_USER = 'userDetails'

COLLECTION_IMAGE_RECORDS = "imageRecords"